# Generated by Django 3.2.6 on 2021-08-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp_name',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
