# Generated by Django 3.2.6 on 2021-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_dp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp_name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
