# Generated by Django 3.2.6 on 2021-08-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_dp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dp_name',
        ),
    ]
