# Generated by Django 3.2.6 on 2021-08-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_dp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dp_name',
            field=models.CharField(default=1, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
